export type SettingScope = "global" | "module" | "user" | "role";
export type SettingValueType = "string" | "number" | "boolean" | "select" | "multi_select" | "json" | "color" | "file" | "date" | "time";

export type AppSetting = { id: string; key: string; module: string; label: string; description?: string; value: string | number | boolean | string[] | Record<string, unknown>; defaultValue: string | number | boolean | string[] | Record<string, unknown>; valueType: SettingValueType; scope: SettingScope; editable: boolean; options?: string[]; isSensitive?: boolean; isEncrypted?: boolean; requiresReload?: boolean; requiresRecalculation?: boolean; requiresPermission?: string; validationRules?: Record<string, unknown>; affectedModules?: string[]; eventName?: string; updatedBy?: string; updatedAt?: string };
export type SettingsModule = { id: string; label: string; description: string; icon: string; eventName: string };
export type SettingsAuditLog = { id: string; settingKey: string; module: string; oldValue: string; newValue: string; userName: string; level: "info" | "warning" | "error" | "critical"; eventName: string; createdAt: string; applied: boolean; requiresRecalculation: boolean };
export type SettingsAction = { id: string; label: string; description: string; category: "sync" | "recalculate" | "system" | "security" | "backup"; requiresConfirmation: boolean; eventName: string };

export const visibleNavigationModules = ["Inicio", "Clientes", "Expedientes", "Presupuestos", "Compras / Proveedores", "Informes", "Ajustes"];

export const settingsModules: SettingsModule[] = [
  { id: "general", label: "General", description: "Empresa, idioma, moneda, fechas y comportamiento base.", icon: "⚙", eventName: "system_settings.updated" },
  { id: "appearance", label: "Apariencia y marca", description: "Colores, logos, sidebar, densidad, radios y gráficos.", icon: "🎨", eventName: "theme.updated" },
  { id: "navigation", label: "Menú y navegación", description: "Siete módulos visibles: documentación, contrato y pago viven dentro de expediente.", icon: "☰", eventName: "navigation.updated" },
  { id: "clients", label: "Clientes y CRM", description: "Dedupe, datos fiscales, origen, Holded e historial de cliente.", icon: "👥", eventName: "client_settings.updated" },
  { id: "cases", label: "Expedientes", description: "Estados, bloqueos, viajeros, documentos, contrato, pago y cierre.", icon: "▣", eventName: "case_settings.updated" },
  { id: "budgets", label: "Presupuestos", description: "Versiones, snapshots, validez, landing y revisión interna.", icon: "📄", eventName: "budget_settings.updated" },
  { id: "margins", label: "Márgenes y precios", description: "Fórmula activa, jerarquía de margen, límites y redondeos.", icon: "%", eventName: "margin_rules.updated" },
  { id: "purchases", label: "Compras / Proveedores", description: "Compras esperadas, matching Holded, tolerancias y no requerida.", icon: "🛒", eventName: "purchase_settings.updated" },
  { id: "documents", label: "Documentación", description: "Retención documental y revisión de documentos dentro de expediente.", icon: "📁", eventName: "document_settings.updated" },
  { id: "contracts", label: "Contrato y pago integrado", description: "Plantillas, firma, pago externo, bloqueo y evidencia dentro del expediente.", icon: "✍", eventName: "contract_payment_settings.updated" },
  { id: "reports", label: "Informes y KPIs", description: "KPIs visibles, objetivos y exportación futura.", icon: "📊", eventName: "report_config.updated" },
  { id: "integrations", label: "Integraciones", description: "Holded, formularios, reservas, pagos, email, storage y calendario.", icon: "🔌", eventName: "integration.updated" },
  { id: "fiscal", label: "Fiscal y contabilidad", description: "Modo fiscal, documentos, IVA, series y revisión de asesoría.", icon: "€", eventName: "fiscal_mode.updated" },
  { id: "security", label: "Seguridad y privacidad", description: "HMAC, tokens, sesiones, RGPD, cifrado y backups.", icon: "🛡", eventName: "security_policy.updated" },
  { id: "logs", label: "Logs y auditoría", description: "Errores, cambios sensibles, reintentos, accesos y acciones técnicas.", icon: "🧾", eventName: "audit_settings.updated" },
  { id: "system", label: "Sistema", description: "Versión, entorno, jobs, caché, métricas, backup y salud.", icon: "🖥", eventName: "system_settings.updated" }
];

export const settingsEvents = ["settings.updated", "settings.reset", "settings.exported", "settings.imported", "theme.updated", "integration.connected", "integration.disconnected", "margin_rules.updated", "fiscal_mode.updated", "report_config.updated", "roles.updated", "security_policy.updated", "system_cache_cleared", "metrics_recalculated"];

export const defaultSettings: AppSetting[] = [
  { id: "company_name", key: "company.name", module: "general", label: "Nombre de la empresa", value: "Routsify", defaultValue: "Routsify", valueType: "string", scope: "global", editable: true, affectedModules: ["documents", "contracts", "emails"] },
  { id: "timezone", key: "company.timezone", module: "general", label: "Zona horaria", value: "(GMT+02:00) Madrid", defaultValue: "(GMT+02:00) Madrid", valueType: "select", options: ["(GMT+02:00) Madrid", "UTC", "Europe/London"], scope: "global", editable: true, requiresRecalculation: true, affectedModules: ["tasks", "reports", "calendar"] },
  { id: "currency", key: "money.currency", module: "general", label: "Moneda por defecto", value: "EUR (€)", defaultValue: "EUR (€)", valueType: "select", options: ["EUR (€)", "USD ($)", "GBP (£)"], scope: "global", editable: true, requiresRecalculation: true, affectedModules: ["budgets", "reports", "payments"] },
  { id: "primary_color", key: "theme.primary", module: "appearance", label: "Color primario", value: "#379237", defaultValue: "#379237", valueType: "color", scope: "global", editable: true, eventName: "theme.updated", affectedModules: ["all"] },
  { id: "sidebar_color", key: "theme.sidebar", module: "appearance", label: "Color sidebar", value: "#14532d", defaultValue: "#14532d", valueType: "color", scope: "global", editable: true, eventName: "theme.updated", affectedModules: ["all"] },
  { id: "nav_modules", key: "navigation.modules", module: "navigation", label: "Módulos visibles", value: visibleNavigationModules, defaultValue: visibleNavigationModules, valueType: "multi_select", scope: "role", editable: true, eventName: "navigation.updated" },
  { id: "client_dedupe_email", key: "clients.dedupe.email", module: "clients", label: "Dedupe por email", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, affectedModules: ["clients", "cases", "integrations"] },
  { id: "client_fiscal_required", key: "clients.fiscal.required", module: "clients", label: "Datos fiscales obligatorios", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, affectedModules: ["clients", "contracts", "fiscal"] },
  { id: "case_close_requires_purchases", key: "cases.close.requires_purchases", module: "cases", label: "Bloquear cierre si hay compras pendientes", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, requiresRecalculation: true, affectedModules: ["cases", "purchases", "reports"] },
  { id: "budget_validity", key: "budgets.validity_days", module: "budgets", label: "Validez por defecto", value: 15, defaultValue: 15, valueType: "number", scope: "global", editable: true, affectedModules: ["budgets", "tasks"] },
  { id: "budget_lock_accepted", key: "budgets.lock_accepted", module: "budgets", label: "Versión aceptada bloquea edición", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, affectedModules: ["budgets", "contracts", "reports"] },
  { id: "margin_formula", key: "margins.formula", module: "margins", label: "Fórmula activa", description: "Margen sobre precio de venta, no markup sobre coste.", value: "margin_on_sale", defaultValue: "margin_on_sale", valueType: "select", options: ["margin_on_sale", "markup_on_cost"], scope: "global", editable: true, requiresRecalculation: true, eventName: "margin_rules.updated", affectedModules: ["budgets", "reports"] },
  { id: "minimum_margin", key: "margins.minimum", module: "margins", label: "Margen mínimo global", value: 12, defaultValue: 12, valueType: "number", scope: "global", editable: true, requiresRecalculation: true, eventName: "margin_rules.updated", affectedModules: ["budgets", "reports"] },
  { id: "purchase_auto_create", key: "purchases.auto_create", module: "purchases", label: "Generar compras esperadas automáticamente", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, affectedModules: ["budgets", "purchases"] },
  { id: "purchase_confidence", key: "purchases.match.min_confidence", module: "purchases", label: "Confianza mínima para sugerir match", value: 70, defaultValue: 70, valueType: "number", scope: "global", editable: true, affectedModules: ["purchases", "reports"] },
  { id: "document_retention", key: "documents.retention", module: "documents", label: "Retención documentos sensibles", value: "5 años", defaultValue: "5 años", valueType: "select", options: ["5 años"], scope: "global", editable: false, affectedModules: ["documents", "security"] },
  { id: "contract_block_fiscal", key: "contracts.block_missing_fiscal", module: "contracts", label: "Bloquear contrato si faltan datos fiscales", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, affectedModules: ["contracts", "clients"] },
  { id: "payment_provider", key: "payments.provider", module: "contracts", label: "Proveedor de pago", value: "Teya manual", defaultValue: "Teya manual", valueType: "select", options: ["Teya manual"], scope: "global", editable: false, affectedModules: ["contracts", "fiscal"] },
  { id: "holded_mode", key: "integrations.holded.mode", module: "integrations", label: "Modo Holded", value: "outbox_idempotent", defaultValue: "outbox_idempotent", valueType: "select", options: ["outbox_idempotent"], scope: "global", editable: false, eventName: "integration.updated", affectedModules: ["holded", "outbox"] },
  { id: "holded_modules", key: "integrations.holded.modules", module: "integrations", label: "Módulos Holded", value: ["contacts", "estimates", "proformas", "invoices", "purchases", "payments"], defaultValue: ["contacts", "estimates", "proformas", "invoices", "purchases", "payments"], valueType: "multi_select", scope: "global", editable: false, affectedModules: ["holded", "outbox"] },
  { id: "ocr_provider", key: "integrations.ocr.provider", module: "integrations", label: "Proveedor OCR", value: "OpenAI", defaultValue: "OpenAI", valueType: "select", options: ["OpenAI"], scope: "global", editable: false, affectedModules: ["documents", "travelers"] },
  { id: "fillout_enabled", key: "integrations.fillout.enabled", module: "integrations", label: "Formularios activos", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, eventName: "integration.updated" },
  { id: "booking_enabled", key: "integrations.booking.enabled", module: "integrations", label: "Reservas activas", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, eventName: "integration.updated" },
  { id: "fiscal_mode", key: "fiscal.mode", module: "fiscal", label: "Modo fiscal", value: "proforma_on_payment_final_after_trip", defaultValue: "proforma_on_payment_final_after_trip", valueType: "select", options: ["proforma_on_payment_final_after_trip"], scope: "global", editable: false, eventName: "fiscal_mode.updated", affectedModules: ["contracts", "holded", "reports"] },
  { id: "final_invoice_delay", key: "fiscal.final_invoice_delay_days", module: "fiscal", label: "Espera para factura final", value: 5, defaultValue: 5, valueType: "number", scope: "global", editable: false, affectedModules: ["fiscal", "close"] },
  { id: "security_hmac", key: "security.webhooks.hmac_required", module: "security", label: "HMAC obligatorio en webhooks", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, eventName: "security_policy.updated", affectedModules: ["integrations"] },
  { id: "logs_retention", key: "logs.retention_days", module: "logs", label: "Retención logs", value: 180, defaultValue: 180, valueType: "number", scope: "global", editable: true, affectedModules: ["audit", "system"] },
  { id: "system_cache", key: "system.cache.enabled", module: "system", label: "Caché de configuración", value: true, defaultValue: true, valueType: "boolean", scope: "global", editable: true, eventName: "system_settings.updated" }
];

export const quickActions: SettingsAction[] = [
  { id: "recalculate-margins", label: "Recalcular márgenes", description: "Recalcula borradores y deja snapshots aceptados intactos.", category: "recalculate", requiresConfirmation: true, eventName: "margin_rules.updated" },
  { id: "view-audit", label: "Ver auditoría de ajustes", description: "Historial de cambios realizados.", category: "security", requiresConfirmation: false, eventName: "settings.updated" }
];

export function moduleFor(id: string) { return settingsModules.find((module) => module.id === id) || settingsModules[0]; }
export function settingsForModule(moduleId: string, settings = defaultSettings) { return settings.filter((setting) => setting.module === moduleId); }
export function filterSettings(settings: AppSetting[], query: string) { const term = query.trim().toLowerCase(); if (!term) return settings; return settings.filter((setting) => [setting.key, setting.module, setting.label, setting.description, String(setting.value)].some((value) => String(value || "").toLowerCase().includes(term))); }
export function settingValueToText(value: AppSetting["value"]) { return Array.isArray(value) ? value.join(", ") : typeof value === "object" ? JSON.stringify(value) : String(value); }
export function settingsSummary(settings = defaultSettings) { return { totalSettings: settings.length, sensitive: settings.filter((setting) => setting.isSensitive).length, recalculations: settings.filter((setting) => setting.requiresRecalculation).length, editable: settings.filter((setting) => setting.editable).length }; }
export function changedSettings(current: AppSetting[], baseline = defaultSettings) { return current.filter((setting) => settingValueToText(setting.value) !== settingValueToText(baseline.find((item) => item.id === setting.id)?.value ?? setting.defaultValue)); }
export function validateSetting(setting: AppSetting) { if (setting.valueType === "number" && Number.isNaN(Number(setting.value))) return `${setting.label} debe ser numérico`; if (setting.valueType === "string" && String(setting.value).trim().length === 0) return `${setting.label} no puede estar vacío`; if (setting.key === "fiscal.mode" && setting.value !== "proforma_on_payment_final_after_trip") return "El modo fiscal debe coincidir con la política validada por asesoría"; return null; }
export function buildAuditFromChange(setting: AppSetting, oldValue: AppSetting["value"], userName = "Sistema"): SettingsAuditLog { return { id: `audit-${Date.now()}-${setting.id}`, settingKey: setting.key, module: setting.module, oldValue: settingValueToText(oldValue), newValue: settingValueToText(setting.value), userName, level: setting.requiresRecalculation || setting.isSensitive ? "warning" : "info", eventName: setting.eventName || moduleFor(setting.module).eventName || "settings.updated", createdAt: "Ahora", applied: true, requiresRecalculation: Boolean(setting.requiresRecalculation) }; }
export function updateSettings(current: AppSetting[], updates: Partial<AppSetting>[]) { const audits: SettingsAuditLog[] = []; const updated = current.map((setting) => { const update = updates.find((item) => item.id === setting.id || item.key === setting.key); if (!update) return setting; const next = { ...setting, ...update, updatedAt: "Ahora", updatedBy: "Sistema" }; audits.push(buildAuditFromChange(next, setting.value)); return next; }); return { settings: updated, audits, events: Array.from(new Set(audits.map((audit) => audit.eventName))), recalculationRequired: audits.some((audit) => audit.requiresRecalculation) }; }
export function resetModule(moduleId: string, settings = defaultSettings) { const updates = settingsForModule(moduleId, settings).map((setting) => ({ ...setting, value: setting.defaultValue })); return updateSettings(settings, updates); }
export function exportSettings(settings = defaultSettings) { return { version: "1.0", exportedAt: new Date().toISOString(), settings: settings.reduce((acc, setting) => ({ ...acc, [setting.key]: setting.value }), {} as Record<string, AppSetting["value"]>) }; }
export function importSettingsPreview(payload: Record<string, unknown>, settings = defaultSettings) { return settings.map((setting) => ({ key: setting.key, currentValue: setting.value, incomingValue: payload[setting.key], valid: payload[setting.key] !== undefined, sensitive: Boolean(setting.isSensitive) })).filter((item) => item.incomingValue !== undefined); }
export function systemInfo() { return { version: "1.1.0", environment: "Producción", database: "PostgreSQL", region: "EU", backupStatus: "Pendiente de política", health: "ok" }; }
