-- Close remaining RLS gaps and remove duplicated permissive policies.
-- No business data is modified.

drop policy if exists automation_rules_select_scoped on public.automation_rules;
create policy automation_rules_select_scoped on public.automation_rules for select to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','operations']::public.app_role[]));
drop policy if exists automation_rules_insert_scoped on public.automation_rules;
create policy automation_rules_insert_scoped on public.automation_rules for insert to authenticated with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists automation_rules_update_scoped on public.automation_rules;
create policy automation_rules_update_scoped on public.automation_rules for update to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[])) with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists automation_rules_delete_scoped on public.automation_rules;
create policy automation_rules_delete_scoped on public.automation_rules for delete to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists automation_executions_select_scoped on public.automation_executions;
create policy automation_executions_select_scoped on public.automation_executions for select to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','operations']::public.app_role[]));
drop policy if exists custom_field_definitions_select_scoped on public.custom_field_definitions;
create policy custom_field_definitions_select_scoped on public.custom_field_definitions for select to authenticated using (organization_id = (select public.current_org_id()));
drop policy if exists custom_field_definitions_insert_scoped on public.custom_field_definitions;
create policy custom_field_definitions_insert_scoped on public.custom_field_definitions for insert to authenticated with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists custom_field_definitions_update_scoped on public.custom_field_definitions;
create policy custom_field_definitions_update_scoped on public.custom_field_definitions for update to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[])) with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists custom_field_definitions_delete_scoped on public.custom_field_definitions;
create policy custom_field_definitions_delete_scoped on public.custom_field_definitions for delete to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists custom_field_values_select_scoped on public.custom_field_values;
create policy custom_field_values_select_scoped on public.custom_field_values for select to authenticated using (organization_id = (select public.current_org_id()));
drop policy if exists custom_field_values_insert_scoped on public.custom_field_values;
create policy custom_field_values_insert_scoped on public.custom_field_values for insert to authenticated with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[]));
drop policy if exists custom_field_values_update_scoped on public.custom_field_values;
create policy custom_field_values_update_scoped on public.custom_field_values for update to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[])) with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[]));
drop policy if exists custom_field_values_delete_scoped on public.custom_field_values;
create policy custom_field_values_delete_scoped on public.custom_field_values for delete to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[]));
drop policy if exists notification_receipts_user_scoped on public.notification_receipts;
create policy notification_receipts_user_scoped on public.notification_receipts for all to authenticated using (organization_id = (select public.current_org_id()) and user_id = (select auth.uid())) with check (organization_id = (select public.current_org_id()) and user_id = (select auth.uid()));
drop policy if exists saved_views_user_scoped on public.saved_views;
create policy saved_views_user_scoped on public.saved_views for all to authenticated using (organization_id = (select public.current_org_id()) and user_id = (select auth.uid())) with check (organization_id = (select public.current_org_id()) and user_id = (select auth.uid()));
drop policy if exists communication_templates_write_scoped on public.communication_templates;
drop policy if exists communication_templates_insert_scoped on public.communication_templates;
create policy communication_templates_insert_scoped on public.communication_templates for insert to authenticated with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists communication_templates_update_scoped on public.communication_templates;
create policy communication_templates_update_scoped on public.communication_templates for update to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[])) with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists communication_templates_delete_scoped on public.communication_templates;
create policy communication_templates_delete_scoped on public.communication_templates for delete to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
drop policy if exists communication_followups_write_scoped on public.communication_followups;
drop policy if exists communication_followups_insert_scoped on public.communication_followups;
create policy communication_followups_insert_scoped on public.communication_followups for insert to authenticated with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[]));
drop policy if exists communication_followups_update_scoped on public.communication_followups;
create policy communication_followups_update_scoped on public.communication_followups for update to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[])) with check (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction','sales','operations','billing']::public.app_role[]));
drop policy if exists communication_followups_delete_scoped on public.communication_followups;
create policy communication_followups_delete_scoped on public.communication_followups for delete to authenticated using (organization_id = (select public.current_org_id()) and (select public.current_app_role()) = any (array['admin','direction']::public.app_role[]));
create index if not exists automation_executions_case_id_idx on public.automation_executions(case_id);
create index if not exists custom_field_values_definition_id_idx on public.custom_field_values(definition_id);
create index if not exists communication_followups_case_id_idx on public.communication_followups(case_id);
create index if not exists communication_followups_client_id_idx on public.communication_followups(client_id);
create index if not exists communication_followups_supplier_id_idx on public.communication_followups(supplier_id);
create index if not exists communication_followups_proposal_id_idx on public.communication_followups(proposal_id);
create index if not exists communication_followups_contract_id_idx on public.communication_followups(contract_id);
create index if not exists communication_followups_purchase_id_idx on public.communication_followups(purchase_id);
create index if not exists communication_followups_template_id_idx on public.communication_followups(template_id);
create index if not exists communication_followups_task_id_idx on public.communication_followups(task_id);

